/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package documentos;

import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author hugov
 */
public class FrmUpload extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmListaProd
     */
    public FrmUpload() {
        initComponents();
        tabelaUpload.getTableHeader().setDefaultRenderer(new principal.EstiloTabelaHeader());
        tabelaUpload.setDefaultRenderer(Object.class, new principal.EstiloTabelaRenderer());
        tabelaUpload.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public int confere;
   

    public final void barra() {
        confere = 0;
        progresso.setValue(0);
        Thread hi = new Thread(() -> {
            while (progresso.getValue() < 100 && confere == 0) {
                try {
                    TimeUnit.MILLISECONDS.sleep(100);
                    progresso.setValue(progresso.getValue() + 2);
                    if (progresso.getValue() == 100) {
                        progresso.setValue(0);
                    }
                } catch (InterruptedException ex) {
                    Logger.getLogger(BarraDeProgresso.class.getName()).log(Level.SEVERE, null, ex);
                }

                if (confere == 1) {
                    progresso.setValue(100);
                }
            }
        });
        hi.start();
    }
    
    void mensagem(){
        int a = 0;
         for (int i = 0; i < tabelaUpload.getRowCount(); i++) {
             String c = tabelaUpload.getValueAt(i, 0).toString();
             if(c.contains("EXISTE")){
                 a = 1;
                 break;
             }
             if(c.contains("ENCONTRADO") || c.equals("") || c.contains("POSSÍVEL")){
                 a = 2;
                 break;
             }
             if(c.contains("EXCLUÍDO")){
                 a = 3;
                 break;
             }
         }
         
        switch (a) {
            case 1:
                JOptionPane.showMessageDialog(this, "Algumas imagens não foram encontradoas na pasta do sistema.\nVocê pode tentar atualizar as imagens do documeto.", "Upload", 0,
                        new ImageIcon(getClass().getResource("/imagens/usuarios/info.png")));
                break;
            case 2:
                JOptionPane.showMessageDialog(this, "Não foi possível fazer o upload.\nVocê pode tentar atualizar a pasta de upload.", "Upload", 0,
                        new ImageIcon(getClass().getResource("/imagens/usuarios/info.png")));
                break;
            case 3:
                JOptionPane.showMessageDialog(this, "Os arquivos foram excluídos do Drive.", "Upload", 0,
                        new ImageIcon(getClass().getResource("/imagens/usuarios/info.png")));
                break;
            default:
                JOptionPane.showMessageDialog(this, "Todos os arquivps foram enviados para o Drive.", "Upload", 0,
                        new ImageIcon(getClass().getResource("/imagens/usuarios/info.png")));
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        tipo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUpload = new javax.swing.JTable();
        progresso = new javax.swing.JProgressBar();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(600, 330));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "UPLOAD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tipo.setText("TIPO");
        jPanel4.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        tabelaUpload.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RESULTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaUpload);
        if (tabelaUpload.getColumnModel().getColumnCount() > 0) {
            tabelaUpload.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 490, 180));
        jPanel4.add(progresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 490, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JProgressBar progresso;
    public javax.swing.JTable tabelaUpload;
    public javax.swing.JLabel tipo;
    // End of variables declaration//GEN-END:variables
}
