/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caixa;

import despesas.*;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author hugov
 */
public class FrmLivroCaixa extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmListaProd
     */
    public static javax.swing.JTable tabela1;
    public FrmLivroCaixa() {
        initComponents();
        tabela.getTableHeader().setDefaultRenderer(new principal.EstiloTabelaHeader());
        tabela.setDefaultRenderer(Object.class, new principal.EstiloTabelaRenderer());
        
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
          
        limparCampos();
    }
    
    void limparCampos() {
        if (tabela.getSelectedRow() > -1) {
            tabela.removeRowSelectionInterval(tabela.getSelectedRow(), tabela.getSelectedRow());
        }
        LivroCaixaSql.listarDataRec("","");
        LivroCaixaSql.listarDataDes("","");
        DefaultTableModel modelo = (DefaultTableModel) FrmLivroCaixa.tabela.getModel();
        tabela.setRowSorter(new TableRowSorter(modelo));
        tabela.getRowSorter().toggleSortOrder(0);
    }
    
    public void preencheTabela(){
        int i;
        
        for (i = 0; i < vendas.FrmCaixa.tabela.getRowCount(); i++) {
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        data1 = new com.toedter.calendar.JDateChooser();
        data3 = new com.toedter.calendar.JDateChooser();
        buscF1 = new javax.swing.JButton();
        emolBrutoT = new javax.swing.JTextField();
        emolBrutoT1 = new javax.swing.JTextField();
        emolBrutoT2 = new javax.swing.JTextField();
        insereDespesa1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(805, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Livro caixa diário auxíliar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATA", "HISTÓRICO", "RECEITA/DESPESA", "VALOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setPreferredWidth(45);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(300);
            tabela.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 730, 240));

        data1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(data1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 150, 30));

        data3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(data3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 150, 30));

        buscF1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buscF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/buscaF1.png"))); // NOI18N
        buscF1.setToolTipText("Buscar");
        buscF1.setBorder(null);
        buscF1.setBorderPainted(false);
        buscF1.setContentAreaFilled(false);
        buscF1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscF1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscF1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/buscaF2.png"))); // NOI18N
        buscF1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buscF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscF1ActionPerformed(evt);
            }
        });
        jPanel4.add(buscF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        emolBrutoT.setBackground(new java.awt.Color(0, 102, 153));
        emolBrutoT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emolBrutoT.setForeground(new java.awt.Color(255, 255, 255));
        emolBrutoT.setToolTipText("");
        emolBrutoT.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emolBrutoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emolBrutoTActionPerformed(evt);
            }
        });
        jPanel4.add(emolBrutoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 110, -1));

        emolBrutoT1.setBackground(new java.awt.Color(0, 102, 153));
        emolBrutoT1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emolBrutoT1.setForeground(new java.awt.Color(255, 255, 255));
        emolBrutoT1.setToolTipText("");
        emolBrutoT1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emolBrutoT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emolBrutoT1ActionPerformed(evt);
            }
        });
        jPanel4.add(emolBrutoT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 110, -1));

        emolBrutoT2.setBackground(new java.awt.Color(0, 102, 153));
        emolBrutoT2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emolBrutoT2.setForeground(new java.awt.Color(255, 255, 255));
        emolBrutoT2.setToolTipText("");
        emolBrutoT2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        emolBrutoT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emolBrutoT2ActionPerformed(evt);
            }
        });
        jPanel4.add(emolBrutoT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 110, -1));

        insereDespesa1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        insereDespesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/PDF.png"))); // NOI18N
        insereDespesa1.setText("EXTRAIR PDF");
        insereDespesa1.setBorder(null);
        insereDespesa1.setBorderPainted(false);
        insereDespesa1.setContentAreaFilled(false);
        insereDespesa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insereDespesa1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        insereDespesa1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        insereDespesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insereDespesa1ActionPerformed(evt);
            }
        });
        jPanel4.add(insereDespesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("RECEITA LÍQUIDA");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("RECEITA BRUTA");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("DESPESAS");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("DE:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("ATÉ:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscF1ActionPerformed

    private void emolBrutoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emolBrutoTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emolBrutoTActionPerformed

    private void emolBrutoT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emolBrutoT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emolBrutoT1ActionPerformed

    private void emolBrutoT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emolBrutoT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emolBrutoT2ActionPerformed

    private void insereDespesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insereDespesa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insereDespesa1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscF1;
    private com.toedter.calendar.JDateChooser data1;
    private com.toedter.calendar.JDateChooser data3;
    private javax.swing.JTextField emolBrutoT;
    private javax.swing.JTextField emolBrutoT1;
    private javax.swing.JTextField emolBrutoT2;
    private javax.swing.JButton insereDespesa1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
