/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caixa;


import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Font;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.BaseFont;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfTable;
import com.lowagie.text.pdf.PdfWriter;

import despesas.*;
import java.awt.Desktop;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author hugov
 */
public class FrmLivroCaixa extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmListaProd
     */
    public static javax.swing.JTable tabela1;
    public FrmLivroCaixa() {
        initComponents();
        tabela.getTableHeader().setDefaultRenderer(new principal.EstiloTabelaHeader());
        tabela.setDefaultRenderer(Object.class, new principal.EstiloTabelaRenderer());
        
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
          
        limparCampos();
    }
    
    void limparCampos() {
        if (tabela.getSelectedRow() > -1) {
            tabela.removeRowSelectionInterval(tabela.getSelectedRow(), tabela.getSelectedRow());
        }
        //LivroCaixaSql.listarDataRec("","");
        //LivroCaixaSql.listarDataDes("","");
        DefaultTableModel modelo = (DefaultTableModel) FrmLivroCaixa.tabela.getModel();
        tabela.setRowSorter(new TableRowSorter(modelo));
        tabela.getRowSorter().toggleSortOrder(0);
    }
    
    void buscar(){
        Date date1 = data1.getDate();
        Date date2 = data2.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("YYY-MM-dd");
        LivroCaixaSql.listarDataRec(String.valueOf(sdf.format(date1)), String.valueOf(sdf.format(date2)));
        LivroCaixaSql.listarDataDes(String.valueOf(sdf.format(date1)), String.valueOf(sdf.format(date2)));
        calcular();
    }

    void calcular() {
        String dataF;
        String receitaS;
        double receita = 0.0;
        double receitaB = 0.0;
        String despesaS;
        double despesa = 0.0;
        double despesaB = 0.0;
        double receitaL = 0.0;
        String roud = null;
        for (int i = 0; i <  FrmLivroCaixa.tabela.getRowCount(); i++) {
            dataF =  FrmLivroCaixa.tabela.getValueAt(i, 0).toString();
            if (dataF.contains("-")) {
                SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
                Date dateF = null;                
                try {
                    dateF = formato.parse(dataF);
                } catch (ParseException ex) {
                    Logger.getLogger(FrmLivroCaixa.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                dataF = String.valueOf(sdf.format(dateF));

                FrmLivroCaixa.tabela.setValueAt(dataF, i, 0);
            }
            
            roud = FrmLivroCaixa.tabela.getValueAt(i, 2).toString();
            if(roud.contains("R")){
                receitaS = FrmLivroCaixa.tabela.getValueAt(i, 3).toString();
                String mostra = receitaS;
                mostra = mostra.replaceAll("\\.", ",");
                FrmLivroCaixa.tabela.setValueAt("R$ "+mostra, i, 3);
                receita = Double.parseDouble(receitaS);
                receitaB += receita;
            }
            if(roud.contains("D")){
                despesaS = FrmLivroCaixa.tabela.getValueAt(i, 3).toString();
                String mostra = despesaS;
                mostra = mostra.replaceAll("\\.", ",");
                FrmLivroCaixa.tabela.setValueAt("R$ "+mostra, i, 3);
                despesa = Double.parseDouble(despesaS);
                despesaB += despesa;
            }
            
        }
        receitaBruta.setText("R$ " + Math.rint(receitaB * 100) / 100);
        despesaBruta.setText("R$ " + Math.rint(despesaB * 100) / 100);
        receitaL = receitaB - despesaB;
        receitaLiquida.setText("R$ " + Math.rint(receitaL * 100) / 100);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        data1 = new com.toedter.calendar.JDateChooser();
        data2 = new com.toedter.calendar.JDateChooser();
        buscF1 = new javax.swing.JButton();
        receitaLiquida = new javax.swing.JTextField();
        receitaBruta = new javax.swing.JTextField();
        despesaBruta = new javax.swing.JTextField();
        extrairPDF = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(805, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Livro caixa diário auxíliar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATA", "HISTÓRICO", "RECEITA/DESPESA", "VALOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setPreferredWidth(45);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(300);
            tabela.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 730, 240));

        data1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(data1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 150, 30));

        data2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(data2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 150, 30));

        buscF1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buscF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/buscaF1.png"))); // NOI18N
        buscF1.setToolTipText("Buscar");
        buscF1.setBorder(null);
        buscF1.setBorderPainted(false);
        buscF1.setContentAreaFilled(false);
        buscF1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscF1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscF1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/buscaF2.png"))); // NOI18N
        buscF1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buscF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscF1ActionPerformed(evt);
            }
        });
        jPanel4.add(buscF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        receitaLiquida.setEditable(false);
        receitaLiquida.setBackground(new java.awt.Color(0, 102, 153));
        receitaLiquida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        receitaLiquida.setForeground(new java.awt.Color(255, 255, 255));
        receitaLiquida.setToolTipText("");
        receitaLiquida.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        receitaLiquida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receitaLiquidaActionPerformed(evt);
            }
        });
        jPanel4.add(receitaLiquida, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 110, -1));

        receitaBruta.setEditable(false);
        receitaBruta.setBackground(new java.awt.Color(0, 102, 153));
        receitaBruta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        receitaBruta.setForeground(new java.awt.Color(255, 255, 255));
        receitaBruta.setToolTipText("");
        receitaBruta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        receitaBruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receitaBrutaActionPerformed(evt);
            }
        });
        jPanel4.add(receitaBruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 110, -1));

        despesaBruta.setEditable(false);
        despesaBruta.setBackground(new java.awt.Color(0, 102, 153));
        despesaBruta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        despesaBruta.setForeground(new java.awt.Color(255, 255, 255));
        despesaBruta.setToolTipText("");
        despesaBruta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        despesaBruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despesaBrutaActionPerformed(evt);
            }
        });
        jPanel4.add(despesaBruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 110, -1));

        extrairPDF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        extrairPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/PDF.png"))); // NOI18N
        extrairPDF.setText("EXTRAIR PDF");
        extrairPDF.setBorder(null);
        extrairPDF.setBorderPainted(false);
        extrairPDF.setContentAreaFilled(false);
        extrairPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        extrairPDF.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        extrairPDF.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        extrairPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extrairPDFActionPerformed(evt);
            }
        });
        jPanel4.add(extrairPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("RECEITA LÍQUIDA");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("RECEITA BRUTA");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("DESPESAS");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("DE:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("ATÉ:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscF1ActionPerformed
         if (data1.getDate() == null && data1.getDate() == null) {
            LivroCaixaSql.listarDataRec("","");
            LivroCaixaSql.listarDataDes("","");
            calcular();
        } else {
            //String formato = data.getDateFormatString();
            buscar();
        }
    }//GEN-LAST:event_buscF1ActionPerformed

    private void receitaLiquidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receitaLiquidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receitaLiquidaActionPerformed

    private void receitaBrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receitaBrutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receitaBrutaActionPerformed

    private void despesaBrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despesaBrutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_despesaBrutaActionPerformed

    private void extrairPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extrairPDFActionPerformed
        if(data1.getDate() != null && data2.getDate() != null){
            Document doc = new Document();
            String nome = null;
            try {
                buscar();
                Date date1F = data1.getDate();
                Date date2F = data2.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                String date1 = String.valueOf(sdf.format(date1F));
                String date2 = String.valueOf(sdf.format(date2F));
                nome = "Relatório caixa do período de "+date1+" até "+date2+".pdf"; 
                PdfWriter.getInstance(doc, new FileOutputStream(nome));

                doc.open();
                PdfPTable tbl = new PdfPTable(new float[] { 20f, 100f, 30f, 20f });
                Font fontH1 = new Font(BaseFont.ASCENT, 9, Font.NORMAL);
                tbl.setTotalWidth(550f);
                tbl.setLockedWidth(true);
                PdfPCell cell = new PdfPCell(new Phrase("DATA",fontH1));
                cell.setBorderWidth(0);
                tbl.addCell(cell);
                cell = new PdfPCell(new Phrase("HISTÓRICO",fontH1));
                cell.setBorderWidth(0);
                tbl.addCell(cell);
                cell = new PdfPCell(new Phrase("RECEITA/DESPESA",fontH1));
                cell.setBorderWidth(0);
                tbl.addCell(cell);
                cell = new PdfPCell(new Phrase("VALOR",fontH1));
                cell.setBorderWidth(0);
                tbl.addCell(cell);
                for (int i = 0; i <  FrmLivroCaixa.tabela.getRowCount(); i++) {
                    cell = new PdfPCell(new Phrase(FrmLivroCaixa.tabela.getValueAt(i, 0).toString(),fontH1));
                    cell.setBorderWidth(0);
                    tbl.addCell(cell);
                    cell = new PdfPCell(new Phrase(FrmLivroCaixa.tabela.getValueAt(i, 1).toString(),fontH1));
                    cell.setBorderWidth(0);
                    tbl.addCell(cell);
                    cell = new PdfPCell(new Phrase(FrmLivroCaixa.tabela.getValueAt(i, 2).toString(),fontH1));
                    cell.setBorderWidth(0);
                    cell.setHorizontalAlignment(1);
                    tbl.addCell(cell);
                    cell = new PdfPCell(new Phrase(FrmLivroCaixa.tabela.getValueAt(i, 3).toString(),fontH1));
                    cell.setBorderWidth(0);
                    tbl.addCell(cell);

                }
                doc.add(tbl);

            } catch (FileNotFoundException | DocumentException ex) {
                Logger.getLogger(FrmLivroCaixa.class.getName()).log(Level.SEVERE, null, ex);
            }
            doc.close();
            try {
                Desktop.getDesktop().open(new java.io.File(nome));
            } catch (IOException ex) {
                Logger.getLogger(FrmLivroCaixa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Insira um período.", "Extrair PDF", 0,
                new ImageIcon(getClass().getResource("/imagens/usuarios/info.png")));
        }
    }//GEN-LAST:event_extrairPDFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscF1;
    private com.toedter.calendar.JDateChooser data1;
    private com.toedter.calendar.JDateChooser data2;
    private javax.swing.JTextField despesaBruta;
    private javax.swing.JButton extrairPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField receitaBruta;
    private javax.swing.JTextField receitaLiquida;
    public static javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
