/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendas;

import despesas.Despesas;
import despesas.DespesasSql;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author hugov
 */
public class FrmEditaDespesa extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmListaProd
     */
    public FrmEditaDespesa() {
        initComponents();
        limparCampos();
    }

    void limparCampos() {

        
        DecimalFormat decimal = new DecimalFormat("#,###,###.00");
        NumberFormatter numFormatter = new NumberFormatter(decimal);
        numFormatter.setFormat(decimal);
        numFormatter.setAllowsInvalid(false);
        DefaultFormatterFactory dfFactory = new DefaultFormatterFactory(numFormatter);
         
        valorDes.setFormatterFactory(dfFactory);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        enviar = new javax.swing.JButton();
        historico = new app.bolivia.swing.JCTextField();
        nomeL = new javax.swing.JLabel();
        codigo = new app.bolivia.swing.JCTextField();
        codigoL = new javax.swing.JLabel();
        data = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        valorDes = new javax.swing.JFormattedTextField();
        nomeL1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(490, 400));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "CADASTRO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enviar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        enviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/editar.png"))); // NOI18N
        enviar.setText("Atualizar despesa");
        enviar.setBorder(null);
        enviar.setBorderPainted(false);
        enviar.setContentAreaFilled(false);
        enviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enviar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        enviar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/editar1.png"))); // NOI18N
        enviar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        jPanel4.add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 130, 100));

        historico.setBackground(new java.awt.Color(34, 102, 145));
        historico.setBorder(null);
        historico.setForeground(new java.awt.Color(255, 255, 255));
        historico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        historico.setOpaque(false);
        historico.setPhColor(new java.awt.Color(255, 255, 255));
        historico.setPlaceholder("HISTÓRICO");
        historico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                historicoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                historicoKeyTyped(evt);
            }
        });
        jPanel4.add(historico, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 180, -1));

        nomeL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/nomeL.png"))); // NOI18N
        jPanel4.add(nomeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 52));

        codigo.setEditable(false);
        codigo.setBackground(new java.awt.Color(34, 102, 145));
        codigo.setBorder(null);
        codigo.setForeground(new java.awt.Color(255, 255, 255));
        codigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codigo.setOpaque(false);
        codigo.setPhColor(new java.awt.Color(255, 255, 255));
        codigo.setPlaceholder("CÓDIGO");
        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });
        jPanel4.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 90, -1));

        codigoL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos/codigoL.png"))); // NOI18N
        jPanel4.add(codigoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 52));

        data.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel4.add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 150, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("DATA");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        valorDes.setBackground(new java.awt.Color(34, 102, 145));
        valorDes.setBorder(null);
        valorDes.setForeground(new java.awt.Color(255, 255, 255));
        valorDes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        valorDes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        valorDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorDesActionPerformed(evt);
            }
        });
        valorDes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valorDesKeyReleased(evt);
            }
        });
        jPanel4.add(valorDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 120, 30));

        nomeL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas/recibi.png"))); // NOI18N
        jPanel4.add(nomeL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, 52));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void historicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_historicoKeyTyped

    }//GEN-LAST:event_historicoKeyTyped

    private void historicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_historicoKeyReleased

    }//GEN-LAST:event_historicoKeyReleased
    
    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        Despesas d = new Despesas();
        Date data1 = data.getDate();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        String dataF = String.valueOf(formato.format(data1));
        System.out.println(dataF);

        d.setData_des(dataF);
        d.setHistorico_des(historico.getText());
        String valorF = valorDes.getText();
        valorF = valorF.replaceAll("\\.", "");
        valorF = valorF.replaceAll(",", ".");
        d.setValor_des(valorF);
        d.setPrimaryKey(codigo.getText());
        int opc = DespesasSql.atualizarDes(d);
            if (opc == 0) {
                JOptionPane.showMessageDialog(this, "O documento não foi atualizado.", "Documentos", 0,
                        new ImageIcon(getClass().getResource("/imagens/usuarios/info.png")));
            }
            if (opc != 0) {
                JOptionPane.showMessageDialog(this, "Registro Atualizado.", "Documentos", 0,
                        new ImageIcon(getClass().getResource("/imagens/usuarios/info.png")));
                limparCampos();
            }
        DespesasSql.listarDepesas("");
        vendas.FrmVendas.calcularDespesas();
        dispose();
    }//GEN-LAST:event_enviarActionPerformed

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoActionPerformed

    private void valorDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorDesActionPerformed

    private void valorDesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorDesKeyReleased
 
    }//GEN-LAST:event_valorDesKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static app.bolivia.swing.JCTextField codigo;
    private javax.swing.JLabel codigoL;
    public static com.toedter.calendar.JDateChooser data;
    private javax.swing.JButton enviar;
    public static app.bolivia.swing.JCTextField historico;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel nomeL;
    private javax.swing.JLabel nomeL1;
    public static javax.swing.JFormattedTextField valorDes;
    // End of variables declaration//GEN-END:variables
}
